extends:
  template: convisoappsec-onpremises-azure-pipelines.yml
  parameters:
    # Required parameters
    convisoSourceBranchTrigger: 'refs/heads/azure_pipelines_template'
    registryDomain: 'convisoappsec.azurecr.io'
    registryServiceConnection: 'registry-service-connection'

    convisoFlowApiUrl: 'https://homologa.conviso.com.br'
    convisoFlowApiKey: $(FLOW_API_KEY)
    convisoFlowProjectCode: 'Kt5p5zKb_zbth0o0'

    # Optional parameters:
    azureAgentsPool: 'Default'
    convisoFlowCliRepository: 'flowcli'
    convisoSastRepository: 'sastbox'
