  
trigger:
  - master  
jobs:
- job: Flow_Appsec_Job
  pool:
    vmImage: 'ubuntu-16.04'
  container:
    image: 'convisoappsec/flowcli'

  steps:
    - bash: |
          flow --version
      env:
         FLOW_API_KEY: $(FLOW_API_KEY)