resources:
  containers:
    -
      container: conviso_sast
      # change to your ACR host
      image: 'convisoappsec.azurecr.io/sastbox'
      # change to your ACR endpoint connection
      endpoint: 'registry-service-connection'

jobs:
  -
    job: Install_Docker_Job

    workspace:
      clean: all

    pool:
      name: Default
      demands:
        - Agent.OS -equals Linux
    steps:
      -
        bash: curl -fsSL https://get.docker.com -o get-docker.sh
      -
        bash: sh get-docker.sh

      -
        bash: sudo usermod -aG docker $USER
      -
        bash: docker info

  -
    job: Flow_Appsec_Job

    dependsOn: Install_Docker_Job

    # refs/heads/master should be changed to refs/heads/<target_branch>
    condition: eq(variables['build.sourceBranch'], 'refs/heads/master')

    workspace:
      clean: all

    pool:
      name: Default
      demands:
        - Agent.OS -equals Linux
        # create the capability docker=/usr/bin/docker
        - docker

    services:
      conviso_sast: conviso_sast

    container:
      # change to your ACR host
      image: 'convisoappsec.azurecr.io/flowcli'
      # change to your ACR endpoint connection
      endpoint: 'registry-service-connection'


    variables:
      # change to your onpremises flow web service url
      FLOW_API_URL: 'https://homologa.conviso.com.br'
      FLOW_PROJECT_CODE: 'Kt5p5zKb_zbth0o0'
      FLOW_SASTBOX_SKIP_LOGIN: 'true'
      # change to your ACR host
      FLOW_SASTBOX_REGISTRY: 'convisoappsec.azurecr.io'

    steps:
      -
        bash: flow --help
        env:
          FLOW_API_KEY: $(FLOW_API_KEY)
      -
        bash: flow sast run --no-send-to-flow
        env:
          FLOW_API_KEY: $(FLOW_API_KEY)
