trigger:
  - master

jobs:
  - job: Flow_Appsec_Job
    pool:
      name: Default
      demands:
        - agent.name -equals ec2-agent
    container:
      image: '172.31.51.201:5000/convisoappsec/flowcli'
    variables:
      FLOW_API_URL: 'https://172.31.51.201'
      FLOW_PROJECT_CODE: 'blyPry2jte8DFLxK'
      FLOW_API_INSECURE: 'true'
    steps:
      - bash: |
            flow deploy create -f env_vars with values > created_deploy_vars
        env:
           FLOW_API_KEY: $(FLOW_API_KEY)
      - bash: |
            cat created_deploy_vars
      - bash: |
            source created_deploy_vars
            flow sast run \
              --start-commit "$FLOW_DEPLOY_PREVIOUS_VERSION_COMMIT" \
              --end-commit "$FLOW_DEPLOY_CURRENT_VERSION_COMMIT"
        env:
           FLOW_API_KEY: $(FLOW_API_KEY)

