extends:
  template: convisoappsec-azure-pipelines.yml
  parameters:
    azureAgentsPool: 'Default'
    convisoSourceBranchTrigger: 'refs/heads/pipeline_using_dockerhub_and_conviso_registry'

    convisoFlowWithSelfSignedCertificate: false
    convisoFlowApiUrl: 'https://homologa.conviso.com.br'
    convisoFlowApiKey: $(FLOW_API_KEY)
    convisoFlowProjectCode: 'hpgP49QPnjRsgbMe'

