parameters:
   - name: azureAgentsPool
     type: string
     displayName: 'The self hosted agents pool to execute Conviso jobs'
     default: Default

   - name: convisoSourceBranchTrigger
     type: string
     displayName: 'The name of the branch that will run actions within Conviso'
     default: 'refs/heads/master'

   - name: convisoFlowApiUrl
     type: string
     displayName: 'The url that points to AppSecFlow'

   - name: convisoFlowApiKey
     type: string
     displayName: 'The flow api token'

   - name: convisoFlowWithSelfSignedCertificate
     type: boolean
     displayName: 'Flag to indicate that flow uses self signed certificate'
     default: false

   - name: convisoFlowProjectCode
     type: string
     displayName: 'The value of the project code'


jobs:
  -
    job: Conviso_Appsec_Flow_Job
    condition: eq(variables['build.sourceBranch'], '${{ parameters.convisoSourceBranchTrigger }}')
    workspace:
      clean: all
   # for test purpose
    pool:
      vmImage: ubuntu-16.04
      #    pool:
      #      name: '${{ parameters.azureAgentsPool }}'
      #      demands:
      #        - Agent.OS -equals Linux
      #        - docker # create the capability docker=/usr/bin/docker

    container:
      image: convisoappsec/flowcli


    variables:
      FLOW_API_URL: '${{ parameters.convisoFlowApiUrl }}'
      FLOW_PROJECT_CODE: '${{ parameters.convisoFlowProjectCode }}'
      FLOW_API_INSECURE: '${{ parameters.convisoFlowWithSelfSignedCertificate }}'

    steps:
      - bash: flow deploy create -f env_vars with values > deploy_env_vars
        env:
          FLOW_API_KEY: '${{ parameters.convisoFlowApiKey }}'

      - bash: |
          source deploy_env_vars
          flow sast run
        env:
          FLOW_API_KEY: '${{ parameters.convisoFlowApiKey }}'

